// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDTp6Crt_92A_wSIM0O7dUuiCdLnLV7DI4',
    appId: '1:359688168567:web:c827b481da1264bdc01272',
    messagingSenderId: '359688168567',
    projectId: 'tiktok-10313',
    authDomain: 'tiktok-10313.firebaseapp.com',
    storageBucket: 'tiktok-10313.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCU-BuJZsVSUmsQJ2QI2BeQcHDC42sW2O4',
    appId: '1:359688168567:android:969640f029e793dfc01272',
    messagingSenderId: '359688168567',
    projectId: 'tiktok-10313',
    storageBucket: 'tiktok-10313.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDopRwHZypmUq2cdMnHMu35b2PGj23cb8w',
    appId: '1:359688168567:ios:de8eddadcc87e1ccc01272',
    messagingSenderId: '359688168567',
    projectId: 'tiktok-10313',
    storageBucket: 'tiktok-10313.appspot.com',
    androidClientId: '359688168567-82onf1dav21eaesh66h6e7gr17rlhjfd.apps.googleusercontent.com',
    iosClientId: '359688168567-qj9icr7ovb9udnulhgivs2nk042fc0hv.apps.googleusercontent.com',
    iosBundleId: 'com.example.tiktok',
  );

}